CREATE TABLE Users(
    u_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    u_login varchar(15) NOT NULL,
    u_name varchar(20) NOT NULL,
    u_lastname varchar(20) NOT NULL,
    u_password varchar(150) NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY (u_id)
);

CREATE TABLE Categories(
    c_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c_name varchar(80) NOT NULL,
    c_user_id int NULL,
    CONSTRAINT PK_Categories PRIMARY KEY (c_id),
    CONSTRAINT FK_Categories_Users FOREIGN KEY (c_user_id) REFERENCES Users (u_id) ON DELETE CASCADE
);

CREATE TABLE TransactionTypes(
    tt_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    tt_name varchar(15) NOT NULL,
    CONSTRAINT PK_TransactionTypes PRIMARY KEY (tt_id)
);

CREATE TABLE Transactions(
    t_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    t_user_id int NOT NULL,
    t_category_id int NOT NULL,
    t_amount int NOT NULL,
    t_date DATETIME NOT NULL,
    t_description varchar(85) NULL,
    t_transaction_type_id int NOT NULL,
    CONSTRAINT PK_Transactions PRIMARY KEY (t_id),
    CONSTRAINT FK_Transactions_UserID FOREIGN KEY (t_user_id) REFERENCES Users (u_id) ON DELETE CASCADE,
    CONSTRAINT FK_Transactions_CategoryID FOREIGN KEY (t_category_id) REFERENCES Categories (c_id) ON DELETE CASCADE,
    CONSTRAINT FK_Transactions_TransactionTypeID FOREIGN KEY (t_transaction_type_id) REFERENCES TransactionTypes (tt_id) ON DELETE NO ACTION
);