CREATE TABLE Users(
    u_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    u_login varchar(15) NOT NULL,
    u_name varchar(20) NOT NULL,
    u_lastname varchar(20) NOT NULL,
    u_password varchar(150) NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY (u_id)
);

CREATE TABLE CategoryTypes(
    ct_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    ct_name varchar(15) NOT NULL,
    CONSTRAINT PK_CategoryTypes PRIMARY KEY (ct_id)
);

CREATE TABLE Categories(
    c_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    c_name varchar(80) NOT NULL,
    c_user_id int NULL,
    c_category_type_id int NOT NULL,
    CONSTRAINT PK_Categories PRIMARY KEY (c_id),
    CONSTRAINT FK_Categories_Users FOREIGN KEY (c_user_id) REFERENCES Users (u_id) ON DELETE CASCADE,
    CONSTRAINT FK_Categories_CategoryTypes FOREIGN KEY (c_category_type_id) REFERENCES CategoryTypes (ct_id) ON DELETE NO ACTION
);

CREATE TABLE Transactions(
    t_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    t_user_id int NOT NULL,
    t_category_id int NOT NULL,
    t_amount int NOT NULL,
    t_date timestamp NOT NULL,
    t_description varchar(85) NULL,
    CONSTRAINT PK_Transactions PRIMARY KEY (t_id),
    CONSTRAINT FK_Transactions_UserID FOREIGN KEY (t_user_id) REFERENCES Users (u_id) ON DELETE CASCADE,
    CONSTRAINT FK_Transactions_CategoryID FOREIGN KEY (t_category_id) REFERENCES Categories (c_id) ON DELETE CASCADE
);