ALTER TABLE CategoryTypes set ct_name = 'Vaults Incomes' WHERE ct_id = 3;
INSERT INTO CategoryTypes (ct_name) VALUES ('Vaults Expenses');

CREATE TABLE Vaults(
    v_id int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    v_name varchar(50) NOT NULL,
    v_user_id int NOT NULL,
    v_amount float NOT NULL DEFAULT 0,
    CONSTRAINT PK_Vaults PRIMARY KEY (v_id),
    CONSTRAINT FK_Vaults_UserID FOREIGN KEY (v_user_id) REFERENCES Users (u_id) ON DELETE CASCADE
);

ALTER TABLE Transactions ADD COLUMN t_vault_id int NULL;

ALTER TABLE Transactions ADD CONSTRAINT FK_Transactions_VaultID FOREIGN KEY(t_vault_id) REFERENCES Vaults (v_id);