version: '3.6'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER : savew
      POSTGRES_DB: savew
      POSTGRES_PASSWORD: savew
    container_name: savew
    volumes:
      - ${PWD}/savewisedb:/docker-entrypoint-initdb.d/
    ports:
      - 5500:5432